{
  imports = [
    ./features/bitwarden.nix
    ./features/calibre.nix
    ./features/desktop.nix
    ./features/devtools.nix
    ./features/gnome.nix
    ./features/diskutils.nix
    ./features/helix.nix
    ./features/hyprland.nix
    ./features/neomutt.nix
    ./features/obsidian.nix
    ./features/openscad.nix
    ./features/orcaslicer.nix
    ./features/printing.nix
    ./features/prismlauncher.nix
    ./features/starship.nix
    ./features/steam.nix
    ./features/terminal.nix
    ./features/xdg.nix
    ./features/yazi.nix
    ./features/zellij.nix

    ./services/fwupd.nix
    ./services/greetd.nix
    ./services/keyd.nix
    ./services/kmscon.nix
    ./services/lightdm.nix
    ./services/sddm.nix
    ./services/ssh.nix
    ./system/audio.nix
    ./system/base.nix
    ./system/desktoputils.nix
    ./system/networking.nix
    ./system/utils.nix
  ];
}
